services:
  - type: web
    name: souschef-api
    env: python
    buildCommand: |
      pip install -r server/requirements.txt
      apt-get update -y && apt-get install -y tesseract-ocr
    startCommand: cd server && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9